### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by aewhite** [Danielhiversen/flux_led#15] opened 2017-01-15 18:06 UTC
1. `led_flux.py` does not exist. 
2. Installing via pip works however however `python -m flux_led` fails with

```
No module named flux_led.__main__; 'flux_led' is a package and cannot be directly executed
```

3. The section `Set warm white, 75%` says to use `-0` but this turns the light off. 

I was able to find a workaround for (1) and (2) by executing `flux_led/__init__.py` directly.

**Comment by tchellomello** [comment] 2017-01-15 20:22
Thanks for reporting it. I tested and the installation via pip worked as expected and I was able to reproduce the issue with `python -m` as well.  

Let's work on this to get this fixed asap

**Comment by tchellomello** [comment] 2017-01-15 21:26
@aewhite  issue reported on item 2 fixed by PR https://github.com/Danielhiversen/flux_led/pull/17. The package has been not yet updated on pypi but you can test it via pip3 git install. Let us know if worked as expected. 

Thank you!

**Comment by tchellomello** [comment] 2017-01-19 06:05
Closing this issue since all problems were fixed. Thank you!

**Closed by tchellomello** 2017-01-19 06:05 UTC
